"""Dashboard routes for services, chatbot configuration, and conversations."""
from typing import Any
from flask import Blueprint, jsonify, request, render_template

# Create blueprint for dashboard routes
dashboard_bp = Blueprint("dashboard", __name__, url_prefix="/dashboard")


@dashboard_bp.route("/services", methods=["GET"])
def get_services() -> dict[str, Any]:
    """Retrieve list of contracted services.
    
    Returns:
        Dictionary containing contracted services data.
    """
    try:
        # Mock data for contracted services
        services = [
            {
                "id": 1,
                "name": "Premium Support Package",
                "client": "Acme Corporation",
                "status": "active",
                "start_date": "2024-01-01",
                "end_date": "2024-12-31",
                "monthly_cost": 500.00,
                "description": "24/7 premium technical support"
            },
            {
                "id": 2,
                "name": "Basic Consulting",
                "client": "TechStart Inc",
                "status": "pending",
                "start_date": "2024-03-01",
                "end_date": "2025-02-28",
                "monthly_cost": 200.00,
                "description": "Monthly consulting hours"
            },
            {
                "id": 3,
                "name": "Enterprise License",
                "client": "Global Systems",
                "status": "cancelled",
                "start_date": "2023-06-01",
                "end_date": "2024-05-31",
                "monthly_cost": 1200.00,
                "description": "Full enterprise feature access"
            }
        ]
        return jsonify({"services": services, "status": "success"})
    except Exception as e:
        return jsonify({"error": str(e), "status": "error"}), 500


@dashboard_bp.route("/services", methods=["POST"])
def create_service() -> tuple[dict[str, Any], int]:
    """Assign/create a new contracted service.
    
    Returns:
        Tuple of response dictionary and HTTP status code.
        
    Raises:
        ValueError: If request data is empty or invalid.
    """
    try:
        data = request.get_json()
        if not data:
            raise ValueError("Service data cannot be empty")
        
        required_fields = ["name", "client"]
        for field in required_fields:
            if field not in data:
                raise ValueError(f"Missing required field: {field}")
        
        new_service = {
            "id": 4,  # In real implementation, this would be generated by database
            "name": data.get("name"),
            "client": data.get("client"),
            "status": data.get("status", "pending"),
            "start_date": data.get("start_date"),
            "end_date": data.get("end_date"),
            "monthly_cost": float(data.get("monthly_cost", 0)) if data.get("monthly_cost") else 0.0,
            "description": data.get("description", ""),
        }
        return jsonify({"service": new_service, "status": "success"}), 201
    except ValueError as e:
        return jsonify({"error": str(e), "status": "error"}), 400
    except Exception as e:
        return jsonify({"error": str(e), "status": "error"}), 500


@dashboard_bp.route("/services/<int:service_id>", methods=["PUT"])
def update_service(service_id: int) -> tuple[dict[str, Any], int]:
    """Edit/update an existing contracted service.
    
    Args:
        service_id: ID of the service to update.
        
    Returns:
        Updated service data.
        
    Raises:
        ValueError: If update data is empty.
    """
    try:
        data = request.get_json()
        if not data:
            raise ValueError("Update data cannot be empty")
        
        updated_service = {
            "id": service_id,
            "name": data.get("name"),
            "client": data.get("client"),
            "status": data.get("status"),
            "start_date": data.get("start_date"),
            "end_date": data.get("end_date"),
            "monthly_cost": float(data.get("monthly_cost", 0)) if data.get("monthly_cost") is not None else None,
            "description": data.get("description"),
        }
        return jsonify({"service": updated_service, "status": "success"})
    except ValueError as e:
        return jsonify({"error": str(e), "status": "error"}), 400
    except Exception as e:
        return jsonify({"error": str(e), "status": "error"}), 500


@dashboard_bp.route("/services/<int:service_id>", methods=["DELETE"])
def delete_service(service_id: int) -> tuple[dict[str, Any], int]:
    """Cancel a contracted service.
    
    Args:
        service_id: ID of the service to cancel.
        
    Returns:
        Tuple of response dictionary and HTTP status code.
    """
    try:
        return jsonify(
            {
                "message": f"Service {service_id} cancelled successfully", 
                "service_id": service_id,
                "status": "cancelled"
            }
        ), 200
    except Exception as e:
        return jsonify({"error": str(e), "status": "error"}), 500


@dashboard_bp.route("/services/tab", methods=["GET"])
def services_tab() -> Any:
    """Render the services tab template with contracted services.
    
    Returns:
        Rendered HTML template.
    """
    try:
        # Mock data for contracted services
        services = [
            {
                "id": 1,
                "name": "Premium Support Package",
                "client": "Acme Corporation",
                "status": "active",
                "start_date": "2024-01-01",
                "end_date": "2024-12-31",
                "monthly_cost": 500.00,
                "description": "24/7 premium technical support"
            },
            {
                "id": 2,
                "name": "Basic Consulting",
                "client": "TechStart Inc",
                "status": "pending",
                "start_date": "2024-03-01",
                "end_date": "2025-02-28",
                "monthly_cost": 200.00,
                "description": "Monthly consulting hours"
            },
            {
                "id": 3,
                "name": "Enterprise License",
                "client": "Global Systems",
                "status": "cancelled",
                "start_date": "2023-06-01",
                "end_date": "2024-05-31",
                "monthly_cost": 1200.00,
                "description": "Full enterprise feature access"
            }
        ]
        return render_template("services/tab.html", services=services)
    except Exception as e:
        return jsonify({"error": str(e), "status": "error"}), 500


@dashboard_bp.route("/chatbot-config", methods=["GET"])
def get_chatbot_config() -> dict[str, Any]:
    """Retrieve chatbot configuration.
    
    Returns:
        Dictionary containing chatbot configuration settings.
    """
    try:
        chatbot_status = "active"
        status_indicator = {
            "value": chatbot_status,
            "label": "Active",
            "color": "green",
        }
        knowledge_file = {
            "name": "support-knowledge-base.pdf",
            "size": "2.4 MB",
            "last_updated": "2024-01-12T14:30:00",
            "status": "indexed",
        }
        config = {
            "id": 1,
            "name": "Support Assistant",
            "description": "Handles customer support questions for dashboard users.",
            "status": chatbot_status,
            "model": "gpt-4",
            "temperature": 0.7,
            "max_tokens": 150,
            "timeout": 30,
            "system_prompt": "You are a helpful assistant.",
            "streaming": True,
            "context_retention": True,
            "context_window": 10,
            "knowledge_file": knowledge_file,
            "status_indicator": status_indicator,
        }
        return jsonify({"config": config, "status": "success"})
    except Exception as e:
        return jsonify({"error": str(e), "status": "error"}), 500


@dashboard_bp.route("/chatbot-config/tab", methods=["GET"])
def chatbot_config_tab() -> Any:
    """Render chatbot configuration tab with chatbot fields and status details."""
    try:
        chatbot_status = "active"
        status_indicator = {
            "value": chatbot_status,
            "label": "Active",
            "color": "green",
        }
        knowledge_file = {
            "name": "support-knowledge-base.pdf",
            "size": "2.4 MB",
            "last_updated": "2024-01-12T14:30:00",
            "status": "indexed",
        }
        chatbot = {
            "id": 1,
            "name": "Support Assistant",
            "description": "Handles customer support questions for dashboard users.",
            "status": chatbot_status,
            "model": "gpt-4",
            "temperature": 0.7,
            "max_tokens": 150,
            "timeout": 30,
            "system_prompt": "You are a helpful assistant.",
            "streaming": True,
            "context_retention": True,
            "context_window": 10,
            "knowledge_file": knowledge_file,
            "status_indicator": status_indicator,
        }
        return render_template(
            "chatbots/config.html",
            chatbot=chatbot,
            knowledge_file=knowledge_file,
            status_indicator=status_indicator,
        )
    except Exception as e:
        return jsonify({"error": str(e), "status": "error"}), 500


@dashboard_bp.route("/chatbot-config", methods=["PUT", "POST"])
def update_chatbot_config() -> tuple[dict[str, Any], int]:
    """Update chatbot configuration.
    
    Returns:
        Updated configuration data.
        
    Raises:
        ValueError: If configuration data is empty or missing required fields.
    """
    try:
        data = request.get_json()
        if not data:
            raise ValueError("Configuration data cannot be empty")
        
        required_fields = ["model", "temperature"]
        for field in required_fields:
            if field not in data:
                raise ValueError(f"Missing required field: {field}")
        
        updated_config = {
            "id": data.get("id", 1),
            "name": data.get("name", "Support Assistant"),
            "description": data.get("description", ""),
            "status": data.get("status", "active"),
            "model": data["model"],
            "temperature": float(data["temperature"]),
            "max_tokens": data.get("max_tokens", 150),
            "timeout": data.get("timeout", 30),
            "system_prompt": data.get("system_prompt", ""),
            "streaming": data.get("streaming", True),
            "context_retention": data.get("context_retention", True),
            "context_window": data.get("context_window", 10),
            "knowledge_file": data.get("knowledge_file"),
            "status_indicator": data.get("status_indicator"),
        }
        return jsonify({"config": updated_config, "status": "success"})
    except ValueError as e:
        return jsonify({"error": str(e), "status": "error"}), 400
    except Exception as e:
        return jsonify({"error": str(e), "status": "error"}), 500


@dashboard_bp.route("/conversations", methods=["GET"])
def get_conversations() -> dict[str, Any]:
    """Retrieve list of conversations.
    
    Returns:
        Dictionary containing conversation summaries.
    """
    try:
        conversations = [
            {"id": 1, "title": "Support Request #123", "last_message": "Thank you for your help", "timestamp": "2024-01-15T10:30:00"},
            {"id": 2, "title": "Sales Inquiry", "last_message": "Can you provide pricing?", "timestamp": "2024-01-15T09:15:00"},
        ]
        return jsonify({"conversations": conversations, "status": "success"})
    except Exception as e:
        return jsonify({"error": str(e), "status": "error"}), 500
